import { Verse } from './types';

export const christianQuotes = [
  { id: 'q1', text: 'Deus não nos ama porque somos bons, mas porque Ele é bom.', author: 'C.S. Lewis' },
  { id: 'q2', text: 'Fizeste-nos para Ti, e inquieto está o nosso coração enquanto não repousar em Ti.', author: 'Santo Agostinho' },
  { id: 'q3', text: 'A ansiedade não esvazia o amanhã de suas tristezas, mas esvazia o hoje de sua força.', author: 'Charles Spurgeon' },
  { id: 'q4', text: 'Ter fé é assinar uma folha em branco e deixar que Deus nela escreva o que quiser.', author: 'Santo Agostinho' },
  { id: 'q5', text: 'Acredito no Cristianismo como acredito que o sol nasce: não apenas porque o vejo, mas porque através dele vejo tudo o mais.', author: 'C.S. Lewis' },
  { id: 'q6', text: 'O que vem à nossa mente quando pensamos em Deus é a coisa mais importante sobre nós.', author: 'A.W. Tozer' },
  { id: 'q7', text: 'A graça barata é o inimigo mortal de nossa igreja.', author: 'Dietrich Bonhoeffer' },
  { id: 'q8', text: 'Aquele que canta reza duas vezes.', author: 'Santo Agostinho' },
  { id: 'q9', text: 'Pela perseverança o caracol chegou à arca.', author: 'Charles Spurgeon' },
  { id: 'q10', text: 'Deus é mais glorificado em nós quando estamos mais satisfeitos Nele.', author: 'John Piper' },
  { id: 'q11', text: 'A cruz não é o fim terrível de uma vida feliz e temente a Deus, mas ela nos encontra no início de nossa comunhão com Cristo.', author: 'Dietrich Bonhoeffer' },
  { id: 'q12', text: 'Um homem que se prostra diante de Deus, pode ficar de pé diante de qualquer um.', author: 'A.W. Tozer' },
  { id: 'q13', text: 'O Filho de Deus se fez homem para possibilitar que os homens se tornem filhos de Deus.', author: 'C.S. Lewis' },
  { id: 'q14', text: 'A medida do amor é amar sem medida.', author: 'Santo Agostinho' },
  { id: 'q15', text: 'Se Cristo não é tudo para você, Ele não é nada para você.', author: 'Charles Spurgeon' },
  { id: 'q16', text: 'O conhecimento de Deus e o conhecimento de nós mesmos estão intimamente ligados.', author: 'João Calvino' },
  { id: 'q17', text: 'A fé é uma confiança viva e ousada na graça de Deus.', author: 'Martinho Lutero' },
  { id: 'q18', text: 'O homem propõe, mas Deus dispõe.', author: 'Tomás de Kempis' },
  { id: 'q19', text: 'Alegria é o negócio sério do céu.', author: 'C.S. Lewis' },
  { id: 'q20', text: 'Deus provê o vento, o homem deve içar a vela.', author: 'Santo Agostinho' },
  { id: 'q21', text: 'Uma Bíblia que está caindo aos pedaços geralmente pertence a alguém que não está.', author: 'Charles Spurgeon' },
  { id: 'q22', text: 'Deus não se curva à nossa pressa.', author: 'A.W. Tozer' },
  { id: 'q23', text: 'O silêncio diante do mal é o próprio mal: Deus não nos terá por inocentes.', author: 'Dietrich Bonhoeffer' },
  { id: 'q24', text: 'Não há um milímetro quadrado em todo o domínio da nossa existência sobre o qual Cristo não clame: "É meu!"', author: 'Abraham Kuyper' },
  { id: 'q25', text: 'Ame e faça o que quiser.', author: 'Santo Agostinho' },
  { id: 'q26', text: 'Estar cristão significa perdoar o inescusável, porque Deus perdoou o inescusável em você.', author: 'C.S. Lewis' },
  { id: 'q27', text: 'O Senhor não nos salva por causa de nossos méritos, mas por causa da Sua misericórdia.', author: 'Charles Spurgeon' },
  { id: 'q28', text: 'Você não tem uma alma. Você é uma alma. Você tem um corpo.', author: 'C.S. Lewis' },
  { id: 'q29', text: 'Não deixe que seus fracassos o definam, deixe que eles o refinem.', author: 'A.W. Tozer' },
  { id: 'q30', text: 'A oração não é pedir. É um anseio da alma. É uma admissão diária da própria fraqueza.', author: 'Mahatma Gandhi' },
  { id: 'q31', text: 'Um coração grato é o começo da grandeza.', author: 'James E. Faust' },
  { id: 'q32', text: 'Deus, dá-me a serenidade para aceitar as coisas que não posso mudar, coragem para mudar as que posso e sabedoria para distinguir entre as duas.', author: 'Reinhold Niebuhr' },
  { id: 'q33', text: 'O amor não faz o mundo girar. O amor é o que faz a viagem valer a pena.', author: 'Franklin P. Jones' },
  { id: 'q34', text: 'O Senhor te guiará continuamente.', author: 'Isaías 58:11' },
  { id: 'q35', text: 'Quando você percebe que Deus te ama, você pode amar os outros.', author: 'Mother Teresa' },
  { id: 'q36', text: 'Deus não exige que tenhamos sucesso, Ele só exige que você tente.', author: 'Madre Teresa de Calcutá' },
  { id: 'q37', text: 'Fé não é saber o que o futuro guarda, mas saber quem guarda o futuro.', author: 'Autor Desconhecido' },
  { id: 'q38', text: 'O perdão é a chave que liberta a alma.', author: 'Billy Graham' },
  { id: 'q39', text: 'Cristo é a resposta, mesmo quando não sabemos a pergunta.', author: 'Corrie ten Boom' },
  { id: 'q40', text: 'Nós não podemos fazer grandes coisas, apenas pequenas coisas com muito amor.', author: 'Madre Teresa de Calcutá' },
  { id: 'q41', text: 'A maior doença do mundo hoje não é a lepra ou a tuberculose, mas sim a sensação de ser indesejado.', author: 'Madre Teresa de Calcutá' },
  { id: 'q42', text: 'Quando colocamos nossos problemas nas mãos de Deus, Ele coloca Sua paz em nossos corações.', author: 'Autor Desconhecido' },
  { id: 'q43', text: 'Confia no Senhor de todo o teu coração, e não te estribes no teu próprio entendimento.', author: 'Provérbios 3:5' },
  { id: 'q44', text: 'A graça de Deus não faz a jornada mais fácil, mas a torna segura.', author: 'Dietrich Bonhoeffer' },
  { id: 'q45', text: 'O amor de Deus nunca falha.', author: 'Corrie ten Boom' },
  { id: 'q46', text: 'Jesus não é uma bengala; Ele é o caminho.', author: 'Leonard Ravenhill' },
  { id: 'q47', text: 'Fé é ousar colocar o seu sonho à prova de Deus.', author: 'Robert Schuller' },
  { id: 'q48', text: 'Não tenha medo do amanhã, pois Deus já está lá.', author: 'Autor Desconhecido' },
  { id: 'q49', text: 'Quem não sabe perdoar não sabe amar.', author: 'Martin Luther King Jr.' },
  { id: 'q50', text: 'A vida cristã não é uma vida livre de problemas, mas uma vida livre de medo.', author: 'A.W. Tozer' },
  { id: 'q51', text: 'Seja forte e corajoso. Não se apavore nem desanime, pois o Senhor, o seu Deus, estará com você por onde você andar.', author: 'Josué 1:9' },
  { id: 'q52', text: 'As bênçãos de Deus não são recompensas por boas ações, são dons de amor.', author: 'Billy Graham' },
  { id: 'q53', text: 'Orar não é pedir coisas, é alinhar seu coração com o coração de Deus.', author: 'Autor Desconhecido' },
  { id: 'q54', text: 'Deus não escolhe pessoas capacitadas, Ele capacita os escolhidos.', author: 'Albert Einstein' },
  { id: 'q55', text: 'Em tudo, dai graças.', author: '1 Tessalonicenses 5:18' },
  { id: 'q56', text: 'Nós aprendemos de nossos erros mais do que de nossos acertos.', author: 'Billy Graham' },
  { id: 'q57', text: 'Onde há amor, há paz. Onde há paz, há Deus.', author: 'Autor Desconhecido' },
  { id: 'q58', text: 'O Senhor é o meu pastor, nada me faltará.', author: 'Salmos 23:1' },
  { id: 'q59', text: 'Se o coração estiver reto perante Deus, os passos serão retos perante os homens.', author: 'John Bunyan' },
  { id: 'q60', text: 'Um homem só é verdadeiramente grande quando está de joelhos diante de Deus.', author: 'Ezra Taft Benson' },
  { id: 'q61', text: 'A esperança em Deus é uma âncora para a alma.', author: 'Hebreus 6:19' },
  { id: 'q62', text: 'Onde quer que o caminho leve, Deus está com você.', author: 'Autor Desconhecido' },
  { id: 'q63', text: 'A Bíblia é o pão diário dos cristãos, não o bolo para ocasiões especiais.', author: 'Autor Desconhecido' },
  { id: 'q64', text: 'Tente não se tornar um homem de sucesso, mas antes tente se tornar um homem de valor.', author: 'Albert Einstein' },
  { id: 'q65', text: 'Quanto mais você lê a Bíblia, mais ela lê você.', author: 'Charles Spurgeon' },
  { id: 'q66', text: 'Eu sou a luz do mundo. Quem me segue, nunca andará em trevas, mas terá a luz da vida.', author: 'João 8:12' },
  { id: 'q67', text: 'Deus é refúgio e fortaleza, socorro bem presente na angústia.', author: 'Salmos 46:1' },
  { id: 'q68', text: 'Tudo posso naquele que me fortalece.', author: 'Filipenses 4:13' },
  { id: 'q69', text: 'A paz de Deus, que excede todo o entendimento, guardará os vossos corações e os vossos sentimentos em Cristo Jesus.', author: 'Filipenses 4:7' },
  { id: 'q70', text: 'Se você não tem intenção de ouvir a Deus, por que deveria esperar que Ele o ouça?', author: 'A.W. Tozer' },
  { id: 'q71', text: 'Não devemos nos contentar em apenas falar com Deus, mas também devemos ouvir o que Ele nos diz.', author: 'João Calvino' },
  { id: 'q72', text: 'Fé não é a crença de que Deus fará o que você quiser. É a crença de que Deus fará o que é certo.', author: 'Max Lucado' },
  { id: 'q73', text: 'A graça de Deus é maior que qualquer pecado nosso.', author: 'Paul Washer' },
  { id: 'q74', text: 'A oração não muda Deus, mas muda aquele que ora.', author: 'Søren Kierkegaard' },
  { id: 'q75', text: 'Você é a única Bíblia que alguns descrentes lerão.', author: 'John MacArthur' },
  { id: 'q76', text: 'Deus te ama do jeito que você é, mas te ama demais para te deixar assim.', author: 'Justo L. González' },
  { id: 'q77', text: 'O verdadeiro amigo é aquele que te aproxima de Deus.', author: 'Santo Agostinho' },
  { id: 'q78', text: 'As promessas de Deus não têm data de validade.', author: 'Corrie ten Boom' },
  { id: 'q79', text: 'Eu não sou o que eu deveria ser, ah, quão diferente eu sou do que eu serei, mas, pela graça de Deus, não sou o que eu costumava ser.', author: 'John Newton' },
  { id: 'q80', text: 'A vontade de Deus nunca irá levá-lo onde a graça de Deus não possa protegê-lo.', author: 'Billy Graham' },
  { id: 'q81', text: 'A nossa maior segurança não está em saber o que vai acontecer, mas em saber quem detém o futuro.', author: 'R.C. Sproul' },
  { id: 'q82', text: 'Você pode ver Deus em todos os lugares se o seu coração estiver preparado.', author: 'A.W. Tozer' },
  { id: 'q83', text: 'Apenas a graça pode nos dar asas para voarmos acima de nós mesmos.', author: 'Santo Agostinho' },
  { id: 'q84', text: 'A fé vê o invisível, acredita no inacreditável e recebe o impossível.', author: 'Corrie ten Boom' },
  { id: 'q85', text: 'Deus é mais glorificado em nós quando estamos mais satisfeitos nEle.', author: 'John Piper' },
  { id: 'q86', text: 'Um homem com Deus é sempre a maioria.', author: 'John Knox' },
  { id: 'q87', text: 'Quem não aprende a depender de Deus, não aprende nada útil.', author: 'J.I. Packer' },
  { id: 'q88', text: 'Pregar o evangelho em todos os momentos, e se for necessário, usar palavras.', author: 'São Francisco de Assis' },
  { id: 'q89', text: 'As lágrimas são orações também, e viajam para Deus quando não podemos falar.', author: 'Charles Spurgeon' },
  { id: 'q90', text: 'Perdão é libertar o prisioneiro e descobrir que o prisioneiro era você.', author: 'Lewis B. Smedes' },
  { id: 'q91', text: 'A melhor maneira de combater o diabo é com a palavra de Deus.', author: 'Martinho Lutero' },
  { id: 'q92', text: 'A cruz não é um acidente, é o plano de Deus.', author: 'Billy Graham' },
  { id: 'q93', text: 'Quando as provações chegam, Deus está nos purificando.', author: 'C.S. Lewis' },
  { id: 'q94', text: 'Tudo o que Deus faz é com um propósito.', author: 'A.W. Pink' },
  { id: 'q95', text: 'A verdadeira paz não é a ausência de tempestades, mas a presença de Deus nas tempestades.', author: 'Desconhecido' },
  { id: 'q96', text: 'O cristão que não ora é um cristão derrotado.', author: 'Leonard Ravenhill' },
  { id: 'q97', text: 'Nunca pare de orar, porque Deus nunca para de ouvir.', author: 'Max Lucado' },
  { id: 'q98', text: 'Confie em Deus, mesmo quando você não entender o caminho.', author: 'C.H. Spurgeon' },
  { id: 'q99', text: 'Deus não faz obras em corações que estão cheios de si mesmos.', author: 'Charles Spurgeon' },
  { id: 'q100', text: 'Você nunca chegará onde Deus quer que você esteja, se continuar dando desculpas de por que não está lá agora.', author: 'Joyce Meyer' },
  { id: 'q101', text: 'Sua vida pode ser a única Bíblia que algumas pessoas irão ler.', author: 'A.W. Tozer' },
  { id: 'q102', text: 'As aflições não apenas revelam quem somos, mas também quem Deus é.', author: 'Timothy Keller' },
  { id: 'q103', text: 'O evangelho nos lembra de que não há pecado maior que a graça.', author: 'John Piper' },
  { id: 'q104', text: 'Somente Cristo pode transformar o luto em dança.', author: 'Jonathan Edwards' },
  { id: 'q105', text: 'Uma alma cheia de Deus não teme a escuridão.', author: 'A.W. Pink' },
  { id: 'q106', text: 'Cristo não apenas sofreu por nós, Ele também venceu por nós.', author: 'Martinho Lutero' },
  { id: 'q107', text: 'Nunca tente viver de uma fé passada. Confie em Deus hoje.', author: 'Charles Spurgeon' },
  { id: 'q108', text: 'Se Deus é o seu parceiro, faça os seus planos GRANDES.', author: 'D.L. Moody' },
  { id: 'q109', text: 'As respostas de Deus são mais sábias do que as nossas perguntas.', author: 'Santo Agostinho' },
  { id: 'q110', text: 'O céu será preenchido com aqueles que sabem que não merecem estar lá.', author: 'C.S. Lewis' },
  { id: 'q111', text: 'Cada gota de sofrimento tem um propósito redentor.', author: 'John Piper' },
  { id: 'q112', text: 'Se não confiarmos em Deus nas pequenas coisas, falharemos nas grandes.', author: 'Hudson Taylor' },
  { id: 'q113', text: 'Não limite o que Deus pode fazer através de você.', author: 'Corrie ten Boom' },
  { id: 'q114', text: 'A maior prova do amor de Deus não é que Ele nos salva da fornalha, mas que Ele entra nela conosco.', author: 'Desconhecido' },
  { id: 'q115', text: 'A verdadeira adoração não se mede pela emoção, mas pela obediência.', author: 'John MacArthur' },
  { id: 'q116', text: 'Fé não é esperar Deus fazer as coisas do seu jeito.', author: 'A.W. Tozer' },
  { id: 'q117', text: 'A fraqueza não é o fim, é o lugar onde Deus começa.', author: 'C.S. Lewis' },
  { id: 'q118', text: 'Deus nunca tem pressa, mas Ele sempre chega na hora certa.', author: 'Charles Spurgeon' },
  { id: 'q119', text: 'Nenhum lugar é seguro fora da vontade de Deus.', author: 'Corrie ten Boom' },
  { id: 'q120', text: 'Orar não é tentar convencer Deus a fazer a nossa vontade, mas nos render à dEle.', author: 'Billy Graham' },
  { id: 'q121', text: 'Não julgue cada dia pela colheita que você colhe, mas pelas sementes que você planta.', author: 'Robert Louis Stevenson' },
  { id: 'q122', text: 'Deus não procura pessoas de sucesso, Ele procura pessoas que se submetem.', author: 'A.W. Tozer' },
  { id: 'q123', text: 'Fé não elimina as perguntas. Mas a fé sabe onde levá-las.', author: 'Elisabeth Elliot' },
  { id: 'q124', text: 'Nossa maior fraqueza pode ser a porta para a força de Deus.', author: 'Hudson Taylor' },
  { id: 'q125', text: 'O arrependimento é o abraço que damos na misericórdia de Deus.', author: 'Martinho Lutero' },
  { id: 'q126', text: 'A glória de Deus não depende da nossa capacidade de compreendê-la.', author: 'John Piper' },
  { id: 'q127', text: 'Nós fomos criados para espelhar a glória de Deus.', author: 'João Calvino' },
  { id: 'q128', text: 'Tudo o que não provém da fé é pecado.', author: 'Apostolo Paulo' },
  { id: 'q129', text: 'A presença de Cristo é o melhor remédio para uma mente agitada.', author: 'J.C. Ryle' },
  { id: 'q130', text: 'O amor incondicional de Deus é a base de nossa esperança.', author: 'Timothy Keller' },
  { id: 'q131', text: 'Quando as coisas parecem estar desmoronando, elas podem estar apenas caindo no lugar certo.', author: 'Desconhecido' },
  { id: 'q132', text: 'Deus nos dá o necessário, nós pedimos o supérfluo.', author: 'Santo Agostinho' },
  { id: 'q133', text: 'A fé é o pássaro que sente a luz e canta quando a madrugada ainda está escura.', author: 'Rabindranath Tagore' },
  { id: 'q134', text: 'Nós sabemos que o mundo é de Deus, por isso nós podemos rir.', author: 'G.K. Chesterton' },
  { id: 'q135', text: 'Sejamos os servos amados do Senhor, cheios de zelo.', author: 'Madre Teresa de Calcutá' },
  { id: 'q136', text: 'Nenhuma verdadeira grandeza pode ser alcançada sem a ajuda de Deus.', author: 'Martinho Lutero' },
  { id: 'q137', text: 'Deus escreve certo por linhas tortas.', author: 'Provérbio Popular' },
  { id: 'q138', text: 'O Espírito Santo não trabalha através de métodos, mas através de pessoas.', author: 'E.M. Bounds' },
  { id: 'q139', text: 'Sem Cristo a vida não tem esperança; sem Cristo a vida não tem sentido.', author: 'Billy Graham' },
  { id: 'q140', text: 'Quando as forças falham, Deus assume o controle.', author: 'Autor Desconhecido' },
  { id: 'q141', text: 'Para o cristão, o melhor ainda está por vir.', author: 'Richard Baxter' },
  { id: 'q142', text: 'Uma alma entregue a Deus não recua.', author: 'João Calvino' },
  { id: 'q143', text: 'Confie que a mesma mão que permite a tempestade, também controla os ventos.', author: 'Desconhecido' },
  { id: 'q144', text: 'Fé não é sentir que Deus está lá. Fé é agir como se Ele estivesse.', author: 'Neil T. Anderson' },
  { id: 'q145', text: 'Tudo coopera para o bem daqueles que amam a Deus.', author: 'Romanos 8:28' },
  { id: 'q146', text: 'Lembre-se: Deus está no controle, mesmo quando a vida parece fora de controle.', author: 'Desconhecido' },
  { id: 'q147', text: 'Deus muitas vezes quebra o nosso coração para salvar a nossa alma.', author: 'John Piper' },
  { id: 'q148', text: 'Não devemos temer as provações, pois é o fogo que purifica o ouro.', author: 'Charles Spurgeon' },
  { id: 'q149', text: 'A verdadeira fé não descansa até estar na presença de Deus.', author: 'A.W. Tozer' },
  { id: 'q150', text: 'Uma Bíblia fechada não alimenta uma alma faminta.', author: 'Desconhecido' },
  { id: 'q151', text: 'Deus não nos salva do sofrimento, Ele nos salva através dele.', author: 'Dietrich Bonhoeffer' },
  { id: 'q152', text: 'A luz de Cristo resplandece mais brilhante nas noites mais escuras.', author: 'Charles Spurgeon' },
  { id: 'q153', text: 'Você nunca entenderá a grandeza de Deus até que veja a sua própria pequenez.', author: 'A.W. Tozer' },
  { id: 'q154', text: 'Deus transforma cicatrizes em estrelas.', author: 'Robert Schuller' },
  { id: 'q155', text: 'Seja a luz no meio da escuridão.', author: 'Mateus 5:14' },
  { id: 'q156', text: 'Quando perdemos o controle, Deus assume o leme.', author: 'Corrie ten Boom' },
  { id: 'q157', text: 'Sua dor de hoje será sua força de amanhã.', author: 'Desconhecido' },
  { id: 'q158', text: 'Somente Cristo pode satisfazer o coração que Ele mesmo criou.', author: 'Billy Graham' },
  { id: 'q159', text: 'Deixe sua fé ser maior que seus medos.', author: 'Hebreus 11:1' },
  { id: 'q160', text: 'Quem vive para agradar aos homens não pode servir a Deus.', author: 'John MacArthur' },
  { id: 'q161', text: 'O tempo investido em oração não é tempo perdido.', author: 'E.M. Bounds' },
  { id: 'q162', text: 'Nenhuma oração é inútil quando dirigida a um Deus amoroso.', author: 'C.S. Lewis' },
  { id: 'q163', text: 'Aquele que perdoa é perdoado.', author: 'Mateus 6:14' },
  { id: 'q164', text: 'Na escola de Cristo, sempre há algo novo para aprender.', author: 'J.C. Ryle' },
  { id: 'q165', text: 'Nada pode separar-nos do amor de Deus.', author: 'Romanos 8:39' },
  { id: 'q166', text: 'O cristão deve ser a Bíblia que o mundo vai ler.', author: 'A.W. Tozer' },
  { id: 'q167', text: 'A fé sobe as escadas que o amor construiu e olha pelas janelas que a esperança abriu.', author: 'Charles Spurgeon' },
  { id: 'q168', text: 'Você diz: Se eu tivesse um pouco mais, estaria satisfeito. Você comete um erro. Se não está satisfeito com o que tem, não estaria satisfeito se a sua porção fosse dobrada.', author: 'Charles Spurgeon' },
  { id: 'q169', text: 'O Senhor nos livre de um cristianismo que não nos faz amar aos outros.', author: 'Charles Spurgeon' },
  { id: 'q170', text: 'Não é o quanto nós temos, mas o quanto nós desfrutamos, que faz a felicidade.', author: 'Charles Spurgeon' },
  { id: 'q171', text: 'Um bom caráter é a melhor lápide. Aqueles que o amaram e foram ajudados por você se lembrarão de você quando os miosótis murcharem.', author: 'Charles Spurgeon' },
  { id: 'q172', text: 'A esperança em si mesma é como uma estrela: não pode ser vista à luz do sol da prosperidade, e só pode ser descoberta na noite da adversidade.', author: 'Charles Spurgeon' },
  { id: 'q173', text: 'O mesmo sol que derrete a cera endurece o barro. E a mesma influência do evangelho que derrete alguns corações à prova de arrependimento, endurece outros em sua obstinação.', author: 'Charles Spurgeon' },
  { id: 'q174', text: 'A dor é o megafone de Deus para despertar um mundo surdo.', author: 'C.S. Lewis' },
  { id: 'q175', text: 'O perdão é uma coisa linda até que você tenha algo para perdoar.', author: 'C.S. Lewis' },
  { id: 'q176', text: 'Um homem não pode diminuir a glória de Deus recusando-se a adorá-lo, mais do que um lunático pode apagar o sol escrevendo a palavra escuridão nas paredes de sua cela.', author: 'C.S. Lewis' },
  { id: 'q177', text: 'Deus não quer algo de nós. Ele simplesmente nos quer.', author: 'C.S. Lewis' },
  { id: 'q178', text: 'O cristão não acha que Deus nos amará porque somos bons, mas que Deus nos fará bons porque nos ama.', author: 'C.S. Lewis' },
  { id: 'q179', text: 'O futuro é algo que todos nós alcançamos a uma velocidade de sessenta minutos por hora, o que quer que façamos, quem quer que sejamos.', author: 'C.S. Lewis' },
  { id: 'q180', text: 'Eu acredito no cristianismo da mesma forma que acredito que o sol nasce, não só porque o vejo, mas porque por ele eu vejo tudo o mais.', author: 'C.S. Lewis' },
  { id: 'q181', text: 'Se você não entende, creia. Para que entendas, crê.', author: 'Santo Agostinho' },
  { id: 'q182', text: 'Ter fé é acreditar naquilo que você não vê; a recompensa dessa fé é ver aquilo em que você acredita.', author: 'Santo Agostinho' },
  { id: 'q183', text: 'Onde há caridade e amor, ali está Deus.', author: 'Santo Agostinho' },
  { id: 'q184', text: 'Deus fornece o vento, mas o homem deve içar as velas.', author: 'Santo Agostinho' },
  { id: 'q185', text: 'A soberba não é grandeza, mas inchaço; e o que está inchado parece grande, mas não é sadio.', author: 'Santo Agostinho' },
  { id: 'q186', text: 'Não saias de ti, volta para dentro de ti mesmo. A verdade habita no homem interior.', author: 'Santo Agostinho' },
  { id: 'q187', text: 'O céu está cheio de respostas para as quais ninguém se deu ao trabalho de fazer perguntas.', author: 'Billy Graham' },
  { id: 'q188', text: 'O pecado é a segunda força mais poderosa do universo, pois foi ele quem enviou Jesus para a cruz. Somente há uma força maior, e essa força é o amor de Deus.', author: 'Billy Graham' },
  { id: 'q189', text: 'Meu lar está no Céu. Eu estou apenas viajando por este mundo.', author: 'Billy Graham' },
  { id: 'q190', text: 'Deus prova Seu amor por nós; naquilo que enquanto ainda éramos pecadores, Cristo morreu por nós.', author: 'Billy Graham' },
  { id: 'q191', text: 'Quando a riqueza se perde, nada se perde. Quando a saúde se perde, algo se perde. Quando o caráter se perde, tudo se perde.', author: 'Billy Graham' },
  { id: 'q192', text: 'Livros não mudam pessoas, parágrafos sim, às vezes até frases.', author: 'John Piper' },
  { id: 'q193', text: 'O amor verdadeiro de Deus é que Ele faça o que for necessário, não importando o custo, para nos ajudar a ser apaixonados por Ele.', author: 'John Piper' },
  { id: 'q194', text: 'Se você não se vê como um grande pecador, nunca verá Jesus como um grande Salvador.', author: 'John Piper' },
  { id: 'q195', text: 'A preocupação é a fé no negativo, confiança no desastre, crença na derrota e o uso da imaginação no pior lugar possível.', author: 'John Piper' },
  { id: 'q196', text: 'O pecado é o que você faz quando seu coração não está satisfeito com Deus.', author: 'John Piper' },
  { id: 'q197', text: 'Mesmo que eu soubesse que amanhã o mundo se tornaria em pedaços, eu ainda plantaria a minha macieira.', author: 'Martinho Lutero' },
  { id: 'q198', text: 'O coração do homem é como um moinho de vento que trabalha.', author: 'Martinho Lutero' },
  { id: 'q199', text: 'Um cão late quando seu dono é atacado. Eu seria um covarde se visse a verdade de Deus ser atacada e permanecesse em silêncio.', author: 'Martinho Lutero' },
  { id: 'q200', text: 'Fiz uma aliança com Deus: que Ele não me mande visões, nem sonhos, nem mesmo anjos. Estou satisfeito com o dom das Escrituras Sagradas, que me dão instrução abundante.', author: 'Martinho Lutero' },
  { id: 'q201', text: 'Pensamentos não pagam impostos.', author: 'Martinho Lutero' },
  { id: 'q202', text: 'Não sei por quais caminhos Deus me conduz, mas conheço bem meu guia.', author: 'Martinho Lutero' },
  { id: 'q203', text: 'Se você não está adorando a Deus no domingo, você também não O está adorando na segunda.', author: 'John MacArthur' },
  { id: 'q204', text: 'O perdão de Deus não é um passe livre para pecar; é um passaporte para a santidade.', author: 'John MacArthur' },
  { id: 'q205', text: 'A evidência da salvação não é a perfeição, mas a direção.', author: 'John MacArthur' },
  { id: 'q206', text: 'A maior prova da conversão de um homem é que ele odeia o que costumava amar e ama o que costumava odiar.', author: 'John MacArthur' },
  { id: 'q207', text: 'Se você pode pecar e não sentir remorso, você não é um filho de Deus.', author: 'John MacArthur' },
  { id: 'q208', text: 'A fé e a obediência estão ligadas no mesmo pacote; aquele que obedece a Deus confia em Deus; e aquele que confia em Deus, obedece a Deus.', author: 'Charles Spurgeon' },
  { id: 'q209', text: 'A moralidade pode manter você fora da prisão, mas só o sangue de Jesus pode mantê-lo fora do inferno.', author: 'Charles Spurgeon' },
  { id: 'q210', text: 'Seja qual for o pretexto, uma vida de oração negligenciada é o primeiro sinal de afastamento de Deus.', author: 'Charles Spurgeon' },
  { id: 'q211', text: 'O Senhor pode até nos permitir passar pelo fogo, mas Ele não permitirá que sejamos consumidos por ele.', author: 'Charles Spurgeon' },
  { id: 'q212', text: 'A maior provação do cristão não é a aflição, mas a prosperidade.', author: 'Charles Spurgeon' },
  { id: 'q213', text: 'Não confie em suas próprias emoções. Elas mudam como o vento. Confie apenas na Palavra de Deus.', author: 'Charles Spurgeon' },
  { id: 'q214', text: 'A oração é a respiração da alma. O cristão que não ora é um cristão morto.', author: 'Charles Spurgeon' },
  { id: 'q215', text: 'A cruz de Cristo é o centro da história do mundo.', author: 'Charles Spurgeon' },
  { id: 'q216', text: 'O amor de Deus não é medido pelo que Ele nos dá, mas pelo que Ele nos perdoa.', author: 'Charles Spurgeon' },
  { id: 'q217', text: 'Um sermão sem Cristo é como um poço sem água.', author: 'Charles Spurgeon' },
  { id: 'q218', text: 'A graça de Deus é a única esperança para o pecador perdido.', author: 'Charles Spurgeon' },
  { id: 'q219', text: 'Deus nunca nos prometeu uma viagem tranquila, mas sim uma chegada segura.', author: 'Charles Spurgeon' },
  { id: 'q220', text: 'A fé é a mão que recebe o perdão de Deus.', author: 'Charles Spurgeon' },
  { id: 'q221', text: 'O arrependimento é a chave que abre a porta da misericórdia de Deus.', author: 'Charles Spurgeon' },
  { id: 'q222', text: 'A santidade não é uma opção, é uma necessidade para o cristão.', author: 'Charles Spurgeon' },
  { id: 'q223', text: 'O cristão deve ser um espelho que reflete o amor de Cristo para o mundo.', author: 'Charles Spurgeon' },
  { id: 'q224', text: 'A vida cristã é uma batalha constante contra o pecado e as tentações.', author: 'Charles Spurgeon' },
  { id: 'q225', text: 'A nossa vitória está garantida em Cristo Jesus.', author: 'Charles Spurgeon' },
  { id: 'q226', text: 'O sofrimento é o cinzel que Deus usa para moldar o nosso caráter.', author: 'Charles Spurgeon' },
  { id: 'q227', text: 'A esperança do cristão não está neste mundo, mas no céu.', author: 'Charles Spurgeon' },
  { id: 'q228', text: 'O sangue de Cristo é a única moeda aceita no céu.', author: 'Charles Spurgeon' },
  { id: 'q229', text: 'A salvação é um dom gratuito de Deus, não algo que possamos conquistar por nossos próprios méritos.', author: 'Charles Spurgeon' },
  { id: 'q230', text: 'O Espírito Santo é o nosso guia e consolador em todas as tribulações.', author: 'Charles Spurgeon' },
  { id: 'q231', text: 'A Igreja é o corpo de Cristo e cada cristão é um membro importante desse corpo.', author: 'Charles Spurgeon' },
  { id: 'q232', text: 'O amor de Deus é incondicional e eterno.', author: 'Charles Spurgeon' },
  { id: 'q233', text: 'A graça de Deus é suficiente para suprir todas as nossas necessidades.', author: 'Charles Spurgeon' },
  { id: 'q234', text: 'A paz de Deus excede todo o entendimento.', author: 'Charles Spurgeon' },
  { id: 'q235', text: 'Quanto maior o desafio, maior será a manifestação da glória de Deus na sua vida.', author: 'Charles Spurgeon' },
  { id: 'q236', text: 'Não se trata de nós, trata-se da grandiosidade Dele.', author: 'Charles Spurgeon' },
  { id: 'q237', text: 'O amor não é afeto afetuoso, mas o desejo firme pelo bem supremo da pessoa amada tanto quanto pode ser obtido.', author: 'C.S. Lewis' },
  { id: 'q238', text: 'O perdão não significa ignorar o que foi feito de errado; significa não usar isso contra a pessoa.', author: 'C.S. Lewis' },
  { id: 'q239', text: 'O amor humano é algo muito precioso, mas não é divino. Ele deve ser santificado e purificado pelo amor divino.', author: 'C.S. Lewis' },
  { id: 'q240', text: 'O orgulho é a raiz de todos os pecados.', author: 'C.S. Lewis' },
  { id: 'q241', text: 'A humildade não é pensar menos de si mesmo, mas pensar em si mesmo menos frequentemente.', author: 'C.S. Lewis' },
  { id: 'q242', text: 'Milagres não são uma interrupção das leis da natureza, mas uma restauração de sua verdadeira ordem.', author: 'C.S. Lewis' },
  { id: 'q243', text: 'Se descobrirmos em nós um desejo que nada neste mundo pode satisfazer, a explicação mais provável é que fomos feitos para outro mundo.', author: 'C.S. Lewis' },
  { id: 'q244', text: 'Deus nos sussurra em nossos prazeres, fala-nos em nossa consciência, mas grita em nossas dores: é o Seu megafone para despertar um mundo surdo.', author: 'C.S. Lewis' },
  { id: 'q245', text: 'Você nunca é velho demais para estabelecer outro objetivo ou sonhar um novo sonho.', author: 'C.S. Lewis' },
  { id: 'q246', text: 'A fé é a arte de nos apegarmos a coisas em que nossa razão já acreditou, apesar da mudança de nossos humores.', author: 'C.S. Lewis' },
  { id: 'q247', text: 'Se eu encontrar em mim mesmo desejos que nada neste mundo possa satisfazer, posso assumir que não fui feito para este mundo.', author: 'C.S. Lewis' },
  { id: 'q248', text: 'Nós somos o que acreditamos que somos.', author: 'C.S. Lewis' },
  { id: 'q249', text: 'As dificuldades muitas vezes preparam as pessoas comuns para um destino extraordinário.', author: 'C.S. Lewis' },
  { id: 'q250', text: 'Não se deve nunca perder o otimismo. É um dever do ser humano.', author: 'C.S. Lewis' },
  { id: 'q251', text: 'Nós vemos o mundo como o mundo não é, mas como nós somos.', author: 'C.S. Lewis' },
  { id: 'q252', text: 'Nenhum de nós pode ajudar a todo mundo, mas todo mundo pode ajudar alguém.', author: 'C.S. Lewis' },
  { id: 'q253', text: 'Deus permite que experimentemos os pontos baixos da vida a fim de nos ensinar lições que não poderíamos aprender de outra forma.', author: 'C.S. Lewis' },
  { id: 'q254', text: 'O que vemos e o que ouvimos depende em grande parte de onde estamos e de que tipo de pessoa nós somos.', author: 'C.S. Lewis' },
  { id: 'q255', text: 'Amar é ser vulnerável.', author: 'C.S. Lewis' },
  { id: 'q256', text: 'Existe algo bom neste mundo, e vale a pena lutar por ele.', author: 'C.S. Lewis' },
  { id: 'q257', text: 'O sol parece para mim muito sem sentido até que eu saiba que ele ilumina todo o resto.', author: 'C.S. Lewis' },
  { id: 'q258', text: 'Os seres humanos são como espelhos. Eles refletem a luz que os atinge.', author: 'C.S. Lewis' },
  { id: 'q259', text: 'O inferno é um estado de espírito: a pessoa se fecha nela mesma, isolando-se completamente de Deus.', author: 'C.S. Lewis' },
  { id: 'q260', text: 'O diabo ri quando nos vê discutindo, porque ele sabe que não estamos pregando o evangelho.', author: 'C.S. Lewis' },
  { id: 'q261', text: 'A verdadeira alegria vem de amar os outros, não a si mesmo.', author: 'C.S. Lewis' },
  { id: 'q262', text: 'Nós somos seres espirituais tendo uma experiência humana.', author: 'C.S. Lewis' },
  { id: 'q263', text: 'Toda a história humana é um longo processo de aprender a amar.', author: 'C.S. Lewis' },
  { id: 'q264', text: 'Ama e faz o que quiseres. Se calares, calarás com amor; se gritares, gritarás com amor; se corrigires, corrigirás com amor; se perdoares, perdoarás com amor.', author: 'Santo Agostinho' },
  { id: 'q265', text: 'Ninguém pode ser perfeitamente bom se não amar.', author: 'Santo Agostinho' },
  { id: 'q266', text: 'Compreender para crer, crer para compreender.', author: 'Santo Agostinho' },
  { id: 'q267', text: 'Deus não espera que sejamos perfeitos, mas sim que estejamos sempre em busca da perfeição.', author: 'Santo Agostinho' },
  { id: 'q268', text: 'O tempo é um rio, e a vida é um barco que nele navega.', author: 'Santo Agostinho' },
  { id: 'q269', text: 'A fé é a raiz da caridade, e a caridade é o fruto da fé.', author: 'Santo Agostinho' },
  { id: 'q270', text: 'A esperança tem duas filhas lindas, a indignação e a coragem; a indignação ensina-nos a não aceitar as coisas como estão; a coragem, a mudá-las.', author: 'Santo Agostinho' },
  { id: 'q271', text: 'Se você quer ser grande, comece sendo pequeno.', author: 'Santo Agostinho' },
  { id: 'q272', text: 'A verdadeira felicidade consiste em amar a Deus e ser amado por Ele.', author: 'Santo Agostinho' },
  { id: 'q273', text: 'A paz é a tranquilidade da ordem.', author: 'Santo Agostinho' },
  { id: 'q274', text: 'A paciência é o companheiro da sabedoria.', author: 'Santo Agostinho' },
  { id: 'q275', text: 'O perdão é a chave que abre a porta do paraíso.', author: 'Santo Agostinho' },
  { id: 'q276', text: 'O sofrimento é o crisol no qual Deus purifica as nossas almas.', author: 'Santo Agostinho' },
  { id: 'q277', text: 'A verdadeira sabedoria consiste em conhecer a si mesmo.', author: 'Santo Agostinho' },
  { id: 'q278', text: 'A amizade é um tesouro inestimável que devemos cultivar com cuidado.', author: 'Santo Agostinho' },
  { id: 'q279', text: 'A oração é o pão da alma.', author: 'Santo Agostinho' },
  { id: 'q280', text: 'Deus não nos criou para que fôssemos infelizes.', author: 'Santo Agostinho' },
  { id: 'q281', text: 'A graça de Deus é como um rio que flui constantemente.', author: 'Santo Agostinho' },
  { id: 'q282', text: 'O pecado é uma doença que só Deus pode curar.', author: 'Santo Agostinho' },
  { id: 'q283', text: 'A confissão é o primeiro passo para a cura da alma.', author: 'Santo Agostinho' },
  { id: 'q284', text: 'A eucaristia é o pão da vida eterna.', author: 'Santo Agostinho' },
  { id: 'q285', text: 'A cruz é o símbolo do amor de Deus por nós.', author: 'Santo Agostinho' },
  { id: 'q286', text: 'A ressurreição de Cristo é a nossa esperança de vida eterna.', author: 'Santo Agostinho' },
  { id: 'q287', text: 'O Espírito Santo é o nosso consolador e guia.', author: 'Santo Agostinho' },
  { id: 'q288', text: 'A Igreja é a barca que nos leva ao porto seguro do céu.', author: 'Santo Agostinho' },
  { id: 'q289', text: 'A Bíblia é a palavra de Deus revelada a nós.', author: 'Santo Agostinho' },
  { id: 'q290', text: 'A salvação é de graça, mas o discipulado custa tudo o que temos.', author: 'Billy Graham' },
  { id: 'q291', text: 'O perdão é a chave que liberta o coração da prisão do ressentimento.', author: 'Billy Graham' },
  { id: 'q292', text: 'A verdadeira paz não é a ausência de conflitos, mas a presença de Deus.', author: 'Billy Graham' },
  { id: 'q293', text: 'O amor de Deus é a única força capaz de transformar o coração humano.', author: 'Billy Graham' },
  { id: 'q294', text: 'A esperança do cristão não está neste mundo, mas na eternidade.', author: 'Billy Graham' },
  { id: 'q295', text: 'A oração é a nossa linha direta com o Criador do universo.', author: 'Billy Graham' },
  { id: 'q296', text: 'O Espírito Santo é a fonte de poder para a vida cristã.', author: 'Billy Graham' },
  { id: 'q297', text: 'A Bíblia é o manual de instruções de Deus para a vida humana.', author: 'Billy Graham' },
  { id: 'q298', text: 'Jesus Cristo é a única esperança para o mundo perdido.', author: 'Billy Graham' },
  { id: 'q299', text: 'A cruz é o símbolo do amor e do sacrifício supremo.', author: 'Billy Graham' },
  { id: 'q300', text: 'O arrependimento é o primeiro passo em direção a Deus.', author: 'Billy Graham' },
  { id: 'q301', text: 'A fé não é uma emoção, mas uma decisão de confiar em Deus.', author: 'Billy Graham' },
  { id: 'q302', text: 'O perdão de Deus é maior do que qualquer pecado que possamos cometer.', author: 'Billy Graham' },
  { id: 'q303', text: 'A graça de Deus é suficiente para todas as nossas necessidades.', author: 'Billy Graham' },
  { id: 'q304', text: 'A alegria do Senhor é a nossa força.', author: 'Billy Graham' },
  { id: 'q305', text: 'O sofrimento pode ser o instrumento que Deus usa para nos aproximar Dele.', author: 'Billy Graham' },
  { id: 'q306', text: 'O amor ao próximo é a evidência do nosso amor a Deus.', author: 'Billy Graham' },
  { id: 'q307', text: 'A missão do cristão é compartilhar o evangelho com o mundo.', author: 'Billy Graham' },
  { id: 'q308', text: 'A Igreja é o corpo de Cristo na terra.', author: 'Billy Graham' },
  { id: 'q309', text: 'O Céu é o lar eterno daqueles que creem em Jesus.', author: 'Billy Graham' },
  { id: 'q310', text: 'Eu li a última página da Bíblia, vai tudo dar certo.', author: 'Billy Graham' },
  { id: 'q311', text: 'Cada vida, por mais longa que seja, é muito curta se comparada com a eternidade.', author: 'Billy Graham' },
  { id: 'q312', text: 'O maior desperdício no mundo é a diferença entre o que somos e o que poderíamos nos tornar.', author: 'Billy Graham' },
  { id: 'q313', text: 'O conforto e a prosperidade nunca enriqueceram o mundo tanto quanto a adversidade.', author: 'Billy Graham' },
  { id: 'q314', text: 'Um cristão de joelhos consegue enxergar mais longe do que um filósofo nas pontas dos pés.', author: 'Billy Graham' },
  { id: 'q315', text: 'Quando a pessoa está em sintonia com Deus, a oração e a leitura da Bíblia se tornam tão vitais quanto o alimento.', author: 'Billy Graham' },
  { id: 'q316', text: 'Deus não nos salva para sermos santos em uma estufa, mas no mundo.', author: 'Billy Graham' },
  { id: 'q317', text: 'Se formos a Cristo em oração, Ele estará conosco em nossas dificuldades.', author: 'Billy Graham' },
  { id: 'q318', text: 'O tempo é o capital de Deus, e Ele nos faz prestadores de contas por ele.', author: 'Billy Graham' },
  { id: 'q319', text: 'Quando chegar a hora de morrer, certifique-se de que tudo que você tenha que fazer é morrer.', author: 'Billy Graham' },
  { id: 'q320', text: 'A missão existe porque a adoração não existe.', author: 'John Piper' },
  { id: 'q321', text: 'Cristo não morreu para perdoar os pecadores para que pudessem continuar vivendo como se Ele não existisse.', author: 'John Piper' },
  { id: 'q322', text: 'A alegria em Deus é a essência da verdadeira adoração.', author: 'John Piper' },
  { id: 'q323', text: 'A palavra de Deus é a arma suprema contra o engano do inimigo.', author: 'John Piper' },
  { id: 'q324', text: 'A verdadeira liberdade não é o direito de fazer o que queremos, mas o poder de fazer o que devemos.', author: 'John Piper' },
  { id: 'q325', text: 'Se o seu Deus é pequeno o suficiente para você compreendê-lo totalmente, ele não é o Deus da Bíblia.', author: 'John Piper' },
  { id: 'q326', text: 'A fé que não resulta em obediência é uma fé morta.', author: 'John Piper' },
  { id: 'q327', text: 'A principal razão para a existência humana é a glória de Deus.', author: 'John Piper' },
  { id: 'q328', text: 'O sofrimento é frequentemente o meio pelo qual Deus nos desperta da nossa complacência.', author: 'John Piper' },
  { id: 'q329', text: 'A oração é a respiração da alma em chamas por Deus.', author: 'John Piper' },
  { id: 'q330', text: 'O evangelho é a boa notícia de que Jesus Cristo pagou a dívida que não podíamos pagar.', author: 'John Piper' },
  { id: 'q331', text: 'A graça de Deus é a fonte de toda verdadeira mudança.', author: 'John Piper' },
  { id: 'q332', text: 'A verdadeira beleza reside na semelhança com Cristo.', author: 'John Piper' },
  { id: 'q333', text: 'O orgulho é a negação da nossa dependência de Deus.', author: 'John Piper' },
  { id: 'q334', text: 'A humildade é a aceitação da nossa verdadeira condição diante de Deus.', author: 'John Piper' },
  { id: 'q335', text: 'O arrependimento não é um evento único, mas um estilo de vida.', author: 'John Piper' },
  { id: 'q336', text: 'A fé é a certeza de que as promessas de Deus são verdadeiras.', author: 'John Piper' },
  { id: 'q337', text: 'O amor de Deus é a força mais poderosa do universo.', author: 'John Piper' },
  { id: 'q338', text: 'A esperança do cristão é uma âncora firme e segura para a alma.', author: 'John Piper' },
  { id: 'q339', text: 'A paixão de Deus por Sua própria glória é a nossa maior garantia.', author: 'John Piper' },
  { id: 'q340', text: 'Para ser útil a Deus, devemos primeiro estar totalmente satisfeitos Nele.', author: 'John Piper' },
  { id: 'q341', text: 'Nenhuma experiência trágica é em vão se você confiar nela para a glória de Deus.', author: 'John Piper' },
  { id: 'q342', text: 'Deus está sempre fazendo mil coisas que você não vê e você nem percebe.', author: 'John Piper' },
  { id: 'q343', text: 'Cristo nos resgatou da maldição da lei para nos dar a bênção da Sua presença.', author: 'John Piper' },
  { id: 'q344', text: 'A santidade não é meramente deixar de pecar, mas um apego intenso ao Senhor.', author: 'John Piper' },
  { id: 'q345', text: 'Adoração é o fim, não missões. Missões existem porque a adoração não existe.', author: 'John Piper' },
  { id: 'q346', text: 'A Bíblia não nos foi dada apenas para informação, mas para transformação.', author: 'John Piper' },
  { id: 'q347', text: 'Uma visão pequena de Deus resulta em uma ansiedade muito grande.', author: 'John Piper' },
  { id: 'q348', text: 'O objetivo da Bíblia não é que conheçamos o livro, mas que conheçamos o Autor.', author: 'John Piper' },
  { id: 'q349', text: 'Ninguém pode ser cristão sem orar, como ninguém pode viver sem respirar.', author: 'Martinho Lutero' },
  { id: 'q350', text: 'Onde o Evangelho não é pregado, não pode haver Igreja.', author: 'Martinho Lutero' },
  { id: 'q351', text: 'A paz, se possível, mas a verdade a qualquer custo.', author: 'Martinho Lutero' },
  { id: 'q352', text: 'O cristão não é senhor de nada, mas servo de todos.', author: 'Martinho Lutero' },
  { id: 'q353', text: 'A justificação pela fé é a pedra angular do evangelho.', author: 'Martinho Lutero' },
  { id: 'q354', text: 'A cruz de Cristo é a nossa única glória.', author: 'Martinho Lutero' },
  { id: 'q355', text: 'O perdão dos pecados é a maior dádiva de Deus.', author: 'Martinho Lutero' },
  { id: 'q356', text: 'A graça de Deus é como um oceano que não pode ser medido.', author: 'Martinho Lutero' },
  { id: 'q357', text: 'A oração é a chave da manhã e a fechadura da noite.', author: 'Martinho Lutero' },
  { id: 'q358', text: 'O Espírito Santo é o nosso mestre e consolador.', author: 'Martinho Lutero' },
  { id: 'q359', text: 'A Bíblia é o livro mais precioso do mundo.', author: 'Martinho Lutero' },
  { id: 'q360', text: 'O amor ao próximo é o reflexo do nosso amor a Deus.', author: 'Martinho Lutero' },
  { id: 'q361', text: 'A fé é um dom de Deus, não uma obra humana.', author: 'Martinho Lutero' },
  { id: 'q362', text: 'A salvação não é conquistada pelas nossas obras, mas pela graça de Deus.', author: 'Martinho Lutero' },
  { id: 'q363', text: 'O pecado é a nossa maior doença, e Cristo é o nosso único médico.', author: 'Martinho Lutero' },
  { id: 'q364', text: 'A Igreja é a assembleia dos santos.', author: 'Martinho Lutero' },
  { id: 'q365', text: 'A vida do cristão é uma jornada de fé.', author: 'Martinho Lutero' },
  { id: 'q366', text: 'A morte não é o fim, mas o começo de uma nova vida com Deus.', author: 'Martinho Lutero' },
  { id: 'q367', text: 'A esperança do cristão está firmada nas promessas de Deus.', author: 'Martinho Lutero' },
  { id: 'q368', text: 'Deus não nos salva porque somos bons, Ele nos salva porque Ele é bom.', author: 'Martinho Lutero' },
  { id: 'q369', text: 'Eu tenho segurado muitas coisas em minhas mãos e perdi todas, mas aquilo que coloquei nas mãos de Deus eu ainda possuo.', author: 'Martinho Lutero' },
  { id: 'q370', text: 'Qualquer ensinamento que não se enquadre nas Escrituras deve ser rejeitado, mesmo que faça chover milagres todos os dias.', author: 'Martinho Lutero' },
  { id: 'q371', text: 'A fé é uma ousada confiança na graça de Deus, tão certa que um homem poderia morrer mil vezes por ela.', author: 'Martinho Lutero' },
  { id: 'q372', text: 'Nossas ações nunca poderão salvar-nos, mas são evidências de que fomos salvos.', author: 'Martinho Lutero' },
  { id: 'q373', text: 'Onde Deus constrói uma igreja, o diabo constrói uma capela ao lado.', author: 'Martinho Lutero' },
  { id: 'q374', text: 'Toda a vida cristã deve ser de arrependimento.', author: 'Martinho Lutero' },
  { id: 'q375', text: 'A música é o melhor bálsamo para as tristezas da mente humana.', author: 'Martinho Lutero' },
  { id: 'q376', text: 'Eu estaria disposto a que queimassem todos os meus livros se pudessem reter apenas as Sagradas Escrituras.', author: 'Martinho Lutero' },
  { id: 'q377', text: 'Pregue a Bíblia inteira. O mundo precisa ouvir todo o conselho de Deus.', author: 'Martinho Lutero' },
  { id: 'q378', text: 'A Bíblia é a única fonte infalível de revelação divina.', author: 'John MacArthur' },
  { id: 'q379', text: 'O evangelho é a mensagem central da Bíblia e a única esperança de salvação.', author: 'John MacArthur' },
  { id: 'q380', text: 'O pecado não é apenas uma violação da lei de Deus, mas uma rebelião contra Ele.', author: 'John MacArthur' },
  { id: 'q381', text: 'A cruz de Cristo é o coração do evangelho e o fundamento da nossa fé.', author: 'John MacArthur' },
  { id: 'q382', text: 'O arrependimento verdadeiro envolve uma mudança de mente e de coração em relação ao pecado.', author: 'John MacArthur' },
  { id: 'q383', text: 'A fé salvadora não é apenas um assentimento intelectual, mas uma confiança total em Cristo.', author: 'John MacArthur' },
  { id: 'q384', text: 'A graça de Deus é o favor imerecido concedido aos pecadores.', author: 'John MacArthur' },
  { id: 'q385', text: 'O perdão dos pecados é a libertação da culpa e da condenação.', author: 'John MacArthur' },
  { id: 'q386', text: 'A santidade é o fruto inevitável da verdadeira fé.', author: 'John MacArthur' },
  { id: 'q387', text: 'A oração é a comunicação vital com Deus.', author: 'John MacArthur' },
  { id: 'q388', text: 'O Espírito Santo é o agente divino da regeneração e santificação.', author: 'John MacArthur' },
  { id: 'q389', text: 'A Igreja é a comunidade dos redimidos.', author: 'John MacArthur' },
  { id: 'q390', text: 'A adoração a Deus é o propósito supremo da existência humana.', author: 'John MacArthur' },
  { id: 'q391', text: 'O amor a Cristo é a principal motivação da vida cristã.', author: 'John MacArthur' },
  { id: 'q392', text: 'O discipulado é o compromisso de seguir a Cristo em todas as áreas da vida.', author: 'John MacArthur' },
  { id: 'q393', text: 'A evangelização é o dever de compartilhar o evangelho com o mundo perdido.', author: 'John MacArthur' },
  { id: 'q394', text: 'A esperança da segunda vinda de Cristo é o consolo do cristão em tempos de provação.', author: 'John MacArthur' },
  { id: 'q395', text: 'O julgamento final é a garantia de que a justiça de Deus será feita.', author: 'John MacArthur' },
  { id: 'q396', text: 'A soberania de Deus é a verdade de que Ele governa sobre todas as coisas.', author: 'John MacArthur' },
  { id: 'q397', text: 'A Palavra de Deus é viva, eficaz e capaz de transformar vidas.', author: 'John MacArthur' },
  { id: 'q398', text: 'Se o seu amor por Cristo não o leva a obedecer a Cristo, o seu amor é falso.', author: 'John MacArthur' },
  { id: 'q399', text: 'O perdão é a garantia de que a justiça foi paga, não ignorada.', author: 'John MacArthur' },
  { id: 'q400', text: 'Deus não promete nos livrar das tempestades, mas promete estar conosco no meio delas.', author: 'John MacArthur' },
  { id: 'q401', text: 'A verdadeira adoração acontece quando nosso coração é cativado pela majestade de Deus.', author: 'John MacArthur' },
  { id: 'q402', text: 'A evidência da salvação não é a perfeição absoluta, mas a direção constante.', author: 'John MacArthur' },
  { id: 'q403', text: 'Fé não é acreditar que Deus fará o que você quer, mas que Deus fará o que é melhor.', author: 'John MacArthur' },
  { id: 'q404', text: 'O pecado é uma força destrutiva, mas a graça de Deus é uma força restauradora muito maior.', author: 'John MacArthur' },
  { id: 'q405', text: 'A alegria cristã não depende de circunstâncias perfeitas, mas de um Salvador perfeito.', author: 'John MacArthur' },
  { id: 'q406', text: 'Nunca diminua o padrão de Deus para justificar suas ações.', author: 'John MacArthur' },
  { id: 'q407', text: 'A maior tragédia da vida não é sofrer, mas viver para si mesmo.', author: 'John MacArthur' },
  { id: 'q408', text: 'Um homem que se inclina diante de Deus saberá se manter de pé diante dos homens.', author: 'A.W. Tozer' },
  { id: 'q409', text: 'Deus nunca usa alguém grandemente até que o teste profundamente.', author: 'A.W. Tozer' },
  { id: 'q410', text: 'Aquele que tem Deus e muitas outras coisas não tem nada a mais do que aquele que tem apenas a Deus.', author: 'A.W. Tozer' },
  { id: 'q411', text: 'Muitos cristãos não têm alegria porque sua fé é mais uma teoria do que um relacionamento.', author: 'A.W. Tozer' },
  { id: 'q412', text: 'Se Deus é o seu parceiro, faça grandes planos.', author: 'D.L. Moody' },
  { id: 'q413', text: 'A Bíblia não nos foi dada para aumentar o nosso conhecimento, mas para mudar as nossas vidas.', author: 'D.L. Moody' },
  { id: 'q414', text: 'Fé é o presente, a confiança é o fruto.', author: 'D.L. Moody' },
  { id: 'q415', text: 'O mundo ainda está para ver o que Deus pode fazer através de um homem totalmente consagrado a Ele.', author: 'D.L. Moody' },
  { id: 'q416', text: 'Eu oro não para que Deus faça a minha vontade, mas para que Ele me ajude a fazer a vontade Dele.', author: 'D.L. Moody' },
  { id: 'q417', text: 'A preocupação não esvazia o amanhã de sua tristeza, ela esvazia o hoje de sua força.', author: 'Corrie ten Boom' },
  { id: 'q418', text: 'Nunca tenha medo de confiar um futuro desconhecido a um Deus conhecido.', author: 'Corrie ten Boom' },
  { id: 'q419', text: 'O perdão é uma ordem divina, não uma opção.', author: 'Corrie ten Boom' },
  { id: 'q420', text: 'A medida de uma vida não é o seu tempo de duração, mas a sua doação.', author: 'Corrie ten Boom' },
  { id: 'q421', text: 'Quando um trem passa por um túnel escuro, você não joga fora a passagem e salta; você senta e confia no maquinista.', author: 'Corrie ten Boom' },
  { id: 'q422', text: 'Não devemos nos preocupar com o que os outros pensam de nós, mas apenas com o que Deus pensa.', author: 'Dietrich Bonhoeffer' },
  { id: 'q423', text: 'A graça barata é o inimigo mortal de nossa igreja. Nossa luta hoje é pela graça preciosa.', author: 'Dietrich Bonhoeffer' },
  { id: 'q424', text: 'A essência do cristianismo não é uma ideia, mas uma pessoa, Jesus Cristo.', author: 'Dietrich Bonhoeffer' },
  { id: 'q425', text: 'O silêncio diante do mal é o próprio mal. Deus não nos terá por inocentes. Não falar é falar. Não agir é agir.', author: 'Dietrich Bonhoeffer' },
  { id: 'q426', text: 'Quem não sabe estar sozinho, cuide-se da comunidade. Quem não sabe estar em comunidade, cuide-se da solidão.', author: 'Dietrich Bonhoeffer' },
  { id: 'q427', text: 'Não há acidentes, apenas providência.', author: 'R.C. Sproul' },
  { id: 'q428', text: 'O que a Bíblia ensina, Deus ensina.', author: 'R.C. Sproul' },
  { id: 'q429', text: 'Cristo é o único mediador entre Deus e os homens, e Sua obra é perfeitamente suficiente.', author: 'R.C. Sproul' },
  { id: 'q430', text: 'Só entendemos o que significa a graça de Deus quando compreendemos quão completamente imerecida ela é.', author: 'R.C. Sproul' },
  { id: 'q431', text: 'Saber que Deus é soberano é a maior fonte de paz na vida cristã.', author: 'R.C. Sproul' },
  { id: 'q432', text: 'Não há paz onde o perdão é rejeitado.', author: 'J.I. Packer' },
  { id: 'q433', text: 'O propósito da igreja não é entreter os santos, mas equipá-los para a obra do ministério.', author: 'J.I. Packer' },
  { id: 'q434', text: 'A medida do nosso amor por Deus é a medida do nosso amor pelos nossos irmãos.', author: 'J.I. Packer' },
  { id: 'q435', text: 'Uma vida sem oração é uma vida sem poder.', author: 'J.I. Packer' },
  { id: 'q436', text: 'Ignorar o estudo sobre Deus é sentenciar-se a tropeçar pela vida com uma venda nos olhos.', author: 'J.I. Packer' },
  { id: 'q437', text: 'A oração não prepara para a obra, ela é a obra.', author: 'E.M. Bounds' },
  { id: 'q438', text: 'Homens procuram por métodos melhores; Deus procura por homens melhores.', author: 'E.M. Bounds' },
  { id: 'q439', text: 'Deus não faz nada a não ser em resposta à oração.', author: 'E.M. Bounds' },
  { id: 'q440', text: 'A igreja está à procura de métodos melhores; Deus está à procura de homens melhores.', author: 'E.M. Bounds' },
  { id: 'q441', text: 'As vitórias espirituais não são conquistadas no campo de batalha, mas no aposento da oração.', author: 'E.M. Bounds' },
  { id: 'q442', text: 'Você não viveu até ter feito algo para alguém que nunca poderá lhe pagar.', author: 'John Bunyan' },
  { id: 'q443', text: 'A oração sincera muitas vezes tem mais poder do que mil sermões.', author: 'John Bunyan' },
  { id: 'q444', text: 'Um homem não cai quando perde sua riqueza, mas quando perde sua fé.', author: 'John Bunyan' },
  { id: 'q445', text: 'As promessas de Deus são como as estrelas; quanto mais escuro o céu, mais elas brilham.', author: 'John Bunyan' },
  { id: 'q446', text: 'O tempo que você passa na presença de Deus nunca é desperdiçado.', author: 'John Bunyan' },
  { id: 'q447', text: 'Senhor, carimba a eternidade em meus olhos.', author: 'Jonathan Edwards' },
  { id: 'q448', text: 'A graça é a única flor que pode crescer na lama do coração humano.', author: 'Jonathan Edwards' },
  { id: 'q449', text: 'Deus é glorificado quando dependemos inteiramente d\'Ele.', author: 'Jonathan Edwards' },
  { id: 'q450', text: 'A oração é a linguagem natural de uma alma faminta.', author: 'Jonathan Edwards' },
  { id: 'q451', text: 'Não busquem grandes coisas para si mesmos, busquem apenas o Reino de Deus.', author: 'Jonathan Edwards' },
  { id: 'q452', text: 'A obra de Deus, feita à maneira de Deus, nunca carecerá dos recursos de Deus.', author: 'Hudson Taylor' },
  { id: 'q453', text: 'Cristo não é um meio para nos levar à glória, Ele é a própria glória.', author: 'Hudson Taylor' },
  { id: 'q454', text: 'Deus usa os homens que são fracos o suficiente para depender dEle.', author: 'Hudson Taylor' },
  { id: 'q455', text: 'Muitas vezes, a nossa impaciência é o maior obstáculo à provisão de Deus.', author: 'Hudson Taylor' },
  { id: 'q456', text: 'Nós servimos a um Deus cujos recursos nunca se esgotam.', author: 'Hudson Taylor' },
  { id: 'q457', text: 'A igreja de hoje quer ser salva do inferno, mas não quer ser salva do pecado.', author: 'Leonard Ravenhill' },
  { id: 'q458', text: 'Um homem que é íntimo de Deus nunca se sente intimidado pelos homens.', author: 'Leonard Ravenhill' },
  { id: 'q459', text: 'Se não houver lágrimas em sua oração, pode haver pouco poder em sua pregação.', author: 'Leonard Ravenhill' },
  { id: 'q460', text: 'A oração pode realizar tudo aquilo que o próprio Deus pode realizar.', author: 'Leonard Ravenhill' },
  { id: 'q461', text: 'O cristianismo não é uma fuga da realidade, mas a verdadeira realidade.', author: 'Leonard Ravenhill' },
  { id: 'q462', text: 'A essência do verdadeiro evangelho é que Jesus Cristo morreu por pecadores.', author: 'Paul Washer' },
  { id: 'q463', text: 'Se o evangelho que você prega não escandaliza os homens, você não está pregando o verdadeiro evangelho.', author: 'Paul Washer' },
  { id: 'q464', text: 'A maior necessidade da igreja hoje é de líderes que temam a Deus mais do que temem os homens.', author: 'Paul Washer' },
  { id: 'q465', text: 'Não importa o que o mundo pensa; o que importa é o que Deus declara na Sua Palavra.', author: 'Paul Washer' },
  { id: 'q466', text: 'A verdadeira conversão muda a maneira como você vê tudo no mundo.', author: 'Paul Washer' },
  { id: 'q467', text: 'O evangelho é a notícia maravilhosa de que somos amados em Cristo além de qualquer imaginação.', author: 'Timothy Keller' },
  { id: 'q468', text: 'Deus vai responder a nossa oração da mesma forma que nós oraríamos se soubéssemos de tudo que Ele sabe.', author: 'Timothy Keller' },
  { id: 'q469', text: 'Seu coração é um ídolo de fábrica, e você tem que substituí-lo constantemente por Cristo.', author: 'Timothy Keller' },
  { id: 'q470', text: 'Se Jesus Cristo não foi ressuscitado dos mortos, toda a nossa fé é uma ilusão.', author: 'Timothy Keller' },
  { id: 'q471', text: 'Cristianismo não trata de se tornar bom; trata de se curar da própria crença na bondade.', author: 'Timothy Keller' },
  { id: 'q472', text: 'Deus o ama como você é, mas se recusa a deixá-lo assim. Ele quer que você seja como Jesus.', author: 'Max Lucado' },
  { id: 'q473', text: 'A fé não é a crença de que Deus fará o que você quer. É a crença de que Deus fará o que é certo.', author: 'Max Lucado' },
  { id: 'q474', text: 'O perdão é a decisão de viver no presente, sem deixar que o passado continue destruindo sua vida.', author: 'Max Lucado' },
  { id: 'q475', text: 'Lembre-se: você é muito especial para Deus. Ele o fez único no universo.', author: 'Max Lucado' },
  { id: 'q476', text: 'Deus vê o seu pior e ainda diz que você é o melhor.', author: 'Max Lucado' },
  { id: 'q477', text: 'Deus não nos deve uma explicação. Nós Lhe devemos obediência.', author: 'Elisabeth Elliot' },
  { id: 'q478', text: 'A vontade de Deus nunca vai te levar onde a graça de Deus não possa te proteger.', author: 'Elisabeth Elliot' },
  { id: 'q479', text: 'Não se trata do que acontece com você, mas de quem está com você.', author: 'Elisabeth Elliot' },
  { id: 'q480', text: 'Fé não elimina a confusão, mas permite que você caminhe por meio dela.', author: 'Elisabeth Elliot' },
  { id: 'q481', text: 'Não perca tempo tentando entender o passado, concentre-se no presente e deixe o futuro nas mãos de Deus.', author: 'Elisabeth Elliot' }
];

export function getRandomQuote(): Verse {
    let unseen: string[] = [];
    let lastAuthor: string | null = null;
    
    try {
        const stored = localStorage.getItem('unseenQuotes');
        if (stored) {
            unseen = JSON.parse(stored);
        }
        lastAuthor = localStorage.getItem('lastQuoteAuthor');
    } catch (e) {
        console.error('Failed to parse unseenQuotes', e);
    }

    // Se estiver vazio ou todos já foram vistos, reseta o ciclo
    if (!unseen || unseen.length === 0) {
        unseen = christianQuotes.map(q => q.id);
    }
    
    // Tenta encontrar uma frase com autor diferente do último (máx 10 tentativas para não travar)
    let randomIndex = Math.floor(Math.random() * unseen.length);
    let quoteId = unseen[randomIndex];
    let quote = christianQuotes.find(q => q.id === quoteId);
    
    let attempts = 0;
    while (quote && quote.author === lastAuthor && unseen.length > 1 && attempts < 10) {
        randomIndex = Math.floor(Math.random() * unseen.length);
        quoteId = unseen[randomIndex];
        quote = christianQuotes.find(q => q.id === quoteId);
        attempts++;
    }

    // Remove o id escolhido da lista de não vistos
    unseen.splice(randomIndex, 1);
    
    try {
        localStorage.setItem('unseenQuotes', JSON.stringify(unseen));
        if (quote) {
            localStorage.setItem('lastQuoteAuthor', quote.author);
        }
    } catch (e) {
        console.error('Failed to save unseenQuotes', e);
    }

    if (!quote) {
        // fallback
        quote = christianQuotes[0];
    }

    return {
        id: quote.id,
        text: quote.text,
        reference: quote.author,
        date: new Date().toISOString(),
    };
}
